### PR TITLE
Only use 'static' if __ORCAC__ is defined, otherwise there is screen corruption on the Atari.

### PR DESCRIPTION
**Pull request by frachel**
Also, fix for #35 MAC address padding.

### CODE REVIEW

**Comment by jeffpiep** [comment]
@frachel , what does the __ORCAC__ symbol indicate?

**Comment by frachel** [comment]
> @frachel , what does the **ORCAC** symbol indicate?

I believe its for one of the Apple targets (IIgs maybe?) that is using a different C compiler. I recall the person that implemented it saying something like there is no stack so local function variables needed to be static.. but that broke some Atari stuff so he #ifdef'd it to only be static if using that Orca C compiler.

**Comment by frachel** [comment]
I assume its this: https://github.com/byteworksinc/ORCA-C

**Comment by tschak909** [comment]
Yup, Orca-C is a C compiler for the Apple IIgs.

**Pull request merged**
